"""add unit_id to uploaded_contents

Revision ID: z3a4b5c6d7e9
Revises: z3a4b5c6d7e8, b4665cbe3b83
Create Date: 2026-02-05 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'z3a4b5c6d7e9'
down_revision = ('z3a4b5c6d7e8', 'b4665cbe3b83')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_contents', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploaded_contents', 'course_units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_contents', type_='foreignkey')
    op.drop_column('uploaded_contents', 'unit_id')
    # ### end Alembic commands ###
