"""add unique_content_id to attachments

Revision ID: z5a6b7c8d9e0
Revises: z4a5b6c7d8e9
Create Date: 2026-02-09 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'z5a6b7c8d9e0'
down_revision = 'b8c9d0e1f2g3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('unique_content_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'unique_contents', ['unique_content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'unique_content_id')
    # ### end Alembic commands ###
